create table device
(
    is_active    boolean not null,
    created_at   timestamp(6),
    id           bigint generated by default as identity,
    member_id    bigint,
    modified_at  timestamp(6),
    device_token varchar(255),
    primary key (id)
);

create table notification
(
    read        boolean not null,
    created_at  timestamp(6),
    id          bigint generated by default as identity,
    member_id   bigint  not null,
    modified_at timestamp(6),
    post_id     bigint,
    screen_type varchar(255) check (screen_type in ('POST', 'MYPOST')),
    title       varchar(255),
    primary key (id)
);

create table setting
(
    enabled      tinyint check (enabled between 0 and 3),
    id           bigint generated by default as identity,
    member_id    bigint,
    setting_type varchar(255) check (setting_type in
                                     ('NOTIFICATION_PER_THUMB', 'NOTIFICATION_PER_10', 'NOTIFICATION_THUMB',
                                      'NOTIFICATION')),
    primary key (id)
);

create table settings_dependent_settings
(
    dependent_setting_id bigint not null,
    setting_id           bigint not null
);

alter table device
    add foreign key (member_id) references member (id);
alter table notification
    add foreign key (member_id) references member (id);
alter table setting
    add foreign key (member_id) references member (id);
alter table settings_dependent_settings
    add foreign key (dependent_setting_id) references member (id);
alter table settings_dependent_settings
    add foreign key (setting_id) references setting (id);
