spring:
  flyway:
    enabled: 'false'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  data:
    redis:
      port: '6379'
      host: localhost
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MySQL
  h2:
    console:
      enabled: 'true'
file:
  dir: src/main/resources/static/img/test_store/
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
domain: http://localhost:8080/images/
